spring:
  profiles:
    active: dev  # 기본적으로 dev 프로파일을 활성화
  datasource:
    url: jdbc:mysql://localhost:3306/kafka_commerce?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    redis:
      host: localhost
      port: 6379

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  port: 8081

jwt:
  secret: kafka-commerce-jwt-secret-key-256-bits-long-1234567890abcdefghijklmnopqrstuvwxyz
  expiration: 3600000 # 1시간
  refresh-expiration: 1209600000 # 14일

logging:
  level:
    com.kafkacommerce: DEBUG 