spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kafka_commerce_dev?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: kafka_commerce_dev
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

logging:
  level:
    root: INFO
    com.kafkacommerce: DEBUG

jwt:
  secret: kafka-commerce-jwt-secret-key-dev-256-bits-long-1234567890abcdefghijklmnopqrstuvwxyz
  expiration: 86400000 # 24시간 